### Get pokemon by name
GET http://localhost:3000/pokemon/ditto
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzZjdjYWUyYjM3MGMwNjg0MDUwOGM2YyIsImdvb2dsZSI6eyJpZCI6IjEwNTA3ODIxODcwNjQ2Mjk3NDI5MSIsIm5hbWUiOiJEYW5pZWwgUmFzbXVzc2VuIiwiZW1haWwiOiJkYW5pZWxyYXNtdXNzZW40MkBnbWFpbC5jb20ifX0sImlhdCI6MTY3NzE4OTc3MSwiZXhwIjoxNjc3MTkzMzcxfQ.A-d724N195TYpNO3On6G8fcY3ZQzgjStMqZ2xyp_i_U

### Post a pokemon
POST http://localhost:3000/pokemon
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzZjdjYWUyYjM3MGMwNjg0MDUwOGM2YyIsImdvb2dsZSI6eyJpZCI6IjEwNTA3ODIxODcwNjQ2Mjk3NDI5MSIsIm5hbWUiOiJEYW5pZWwgUmFzbXVzc2VuIiwiZW1haWwiOiJkYW5pZWxyYXNtdXNzZW40MkBnbWFpbC5jb20ifX0sImlhdCI6MTY3NzE4OTc3MSwiZXhwIjoxNjc3MTkzMzcxfQ.A-d724N195TYpNO3On6G8fcY3ZQzgjStMqZ2xyp_i_U
content-type: application/json

{
	"name": "Eevee",
	"types": ["normal"],
	"generation": 1,
	"pokedex_number": 133,
	"height": "1'00\"",
	"weight": "14.3 lbs.",
	"evolve_from": null,
	"evolve_to": ["Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Leafeon", "Glaceon", "Sylveon"]
}

### Put a pokemon
PUT http://localhost:3000/pokemon/63e569ca1c4aceba55eb9975
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzZjdjYWUyYjM3MGMwNjg0MDUwOGM2YyIsImdvb2dsZSI6eyJpZCI6IjEwNTA3ODIxODcwNjQ2Mjk3NDI5MSIsIm5hbWUiOiJEYW5pZWwgUmFzbXVzc2VuIiwiZW1haWwiOiJkYW5pZWxyYXNtdXNzZW40MkBnbWFpbC5jb20ifX0sImlhdCI6MTY3NzE4OTc3MSwiZXhwIjoxNjc3MTkzMzcxfQ.A-d724N195TYpNO3On6G8fcY3ZQzgjStMqZ2xyp_i_U
content-type: application/json

{
	"name": "eevee",
	"types": ["normal"],
	"generation": 1,
	"pokedex_number": 133,
	"height": "1'00\"",
	"weight": "14.3 lbs.",
	"evolve_from": null,
	"evolve_to": ["Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Leafeon", "Glaceon", "Sylveon"]
}
### Delete a pokemon
DELETE http://localhost:3000/pokemon/63e569ad1c4aceba55eb9974





### Get move by name
GET http://localhost:3000/moves/transform
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzZjdjYWUyYjM3MGMwNjg0MDUwOGM2YyIsImdvb2dsZSI6eyJpZCI6IjEwNTA3ODIxODcwNjQ2Mjk3NDI5MSIsIm5hbWUiOiJEYW5pZWwgUmFzbXVzc2VuIiwiZW1haWwiOiJkYW5pZWxyYXNtdXNzZW40MkBnbWFpbC5jb20ifX0sImlhdCI6MTY3NzE4OTc3MSwiZXhwIjoxNjc3MTkzMzcxfQ.A-d724N195TYpNO3On6G8fcY3ZQzgjStMqZ2xyp_i_U

### Post a move
POST http://localhost:3000/moves
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzZjdjYWUyYjM3MGMwNjg0MDUwOGM2YyIsImdvb2dsZSI6eyJpZCI6IjEwNTA3ODIxODcwNjQ2Mjk3NDI5MSIsIm5hbWUiOiJEYW5pZWwgUmFzbXVzc2VuIiwiZW1haWwiOiJkYW5pZWxyYXNtdXNzZW40MkBnbWFpbC5jb20ifX0sImlhdCI6MTY3NzE4OTc3MSwiZXhwIjoxNjc3MTkzMzcxfQ.A-d724N195TYpNO3On6G8fcY3ZQzgjStMqZ2xyp_i_U
content-type: application/json

{
	"name": "Charm",
	"type": "fairy",
	"power": "N/A",
	"accuracy": "100%"
}

### Put a move
PUT http://localhost:3000/moves/63e56acce9b49a71b8076493
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzZjdjYWUyYjM3MGMwNjg0MDUwOGM2YyIsImdvb2dsZSI6eyJpZCI6IjEwNTA3ODIxODcwNjQ2Mjk3NDI5MSIsIm5hbWUiOiJEYW5pZWwgUmFzbXVzc2VuIiwiZW1haWwiOiJkYW5pZWxyYXNtdXNzZW40MkBnbWFpbC5jb20ifX0sImlhdCI6MTY3NzE4OTc3MSwiZXhwIjoxNjc3MTkzMzcxfQ.A-d724N195TYpNO3On6G8fcY3ZQzgjStMqZ2xyp_i_U
content-type: application/json

{
	"name": "charm",
	"type": "fairy",
	"power": "N/A",
	"accuracy": "100%"
}
### Delete a move
DELETE http://localhost:3000/moves/63e56acce9b49a71b8076493
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzZjdjYWUyYjM3MGMwNjg0MDUwOGM2YyIsImdvb2dsZSI6eyJpZCI6IjEwNTA3ODIxODcwNjQ2Mjk3NDI5MSIsIm5hbWUiOiJEYW5pZWwgUmFzbXVzc2VuIiwiZW1haWwiOiJkYW5pZWxyYXNtdXNzZW40MkBnbWFpbC5jb20ifX0sImlhdCI6MTY3NzE4OTc3MSwiZXhwIjoxNjc3MTkzMzcxfQ.A-d724N195TYpNO3On6G8fcY3ZQzgjStMqZ2xyp_i_U














### Get pokemon by name
GET https://pokemonapi-mwwn.onrender.com/pokemon/ditto
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzZjdjYWUyYjM3MGMwNjg0MDUwOGM2YyIsImdvb2dsZSI6eyJpZCI6IjEwNTA3ODIxODcwNjQ2Mjk3NDI5MSIsIm5hbWUiOiJEYW5pZWwgUmFzbXVzc2VuIiwiZW1haWwiOiJkYW5pZWxyYXNtdXNzZW40MkBnbWFpbC5jb20ifX0sImlhdCI6MTY3NzE4OTc3MSwiZXhwIjoxNjc3MTkzMzcxfQ.A-d724N195TYpNO3On6G8fcY3ZQzgjStMqZ2xyp_i_U

### Post a pokemon
POST https://pokemonapi-mwwn.onrender.com/pokemon
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzZjdjYWUyYjM3MGMwNjg0MDUwOGM2YyIsImdvb2dsZSI6eyJpZCI6IjEwNTA3ODIxODcwNjQ2Mjk3NDI5MSIsIm5hbWUiOiJEYW5pZWwgUmFzbXVzc2VuIiwiZW1haWwiOiJkYW5pZWxyYXNtdXNzZW40MkBnbWFpbC5jb20ifX0sImlhdCI6MTY3NzE4OTc3MSwiZXhwIjoxNjc3MTkzMzcxfQ.A-d724N195TYpNO3On6G8fcY3ZQzgjStMqZ2xyp_i_U
content-type: application/json

{
	"name": "Eevee",
	"types": ["normal"],
	"generation": 1,
	"pokedex_number": 133,
	"height": "1'00\"",
	"weight": "14.3 lbs.",
	"evolve_from": null,
	"evolve_to": ["Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Leafeon", "Glaceon", "Sylveon"]
}

### Put a pokemon
PUT https://pokemonapi-mwwn.onrender.com/pokemon/63ded282b5bc56d7c9c3ca93
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzZjdjYWUyYjM3MGMwNjg0MDUwOGM2YyIsImdvb2dsZSI6eyJpZCI6IjEwNTA3ODIxODcwNjQ2Mjk3NDI5MSIsIm5hbWUiOiJEYW5pZWwgUmFzbXVzc2VuIiwiZW1haWwiOiJkYW5pZWxyYXNtdXNzZW40MkBnbWFpbC5jb20ifX0sImlhdCI6MTY3NzE4OTc3MSwiZXhwIjoxNjc3MTkzMzcxfQ.A-d724N195TYpNO3On6G8fcY3ZQzgjStMqZ2xyp_i_U
content-type: application/json

{
	"name": "eevee",
	"types": ["normal"],
	"generation": 1,
	"pokedex_number": 133,
	"height": "1'00\"",
	"weight": "14.3 lbs.",
	"evolve_from": null,
	"evolve_to": ["Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Leafeon", "Glaceon", "Sylveon"]
}
### Delete a pokemon
DELETE https://pokemonapi-mwwn.onrender.com/pokemon/63ded282b5bc56d7c9c3ca93
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzZjdjYWUyYjM3MGMwNjg0MDUwOGM2YyIsImdvb2dsZSI6eyJpZCI6IjEwNTA3ODIxODcwNjQ2Mjk3NDI5MSIsIm5hbWUiOiJEYW5pZWwgUmFzbXVzc2VuIiwiZW1haWwiOiJkYW5pZWxyYXNtdXNzZW40MkBnbWFpbC5jb20ifX0sImlhdCI6MTY3NzE4OTc3MSwiZXhwIjoxNjc3MTkzMzcxfQ.A-d724N195TYpNO3On6G8fcY3ZQzgjStMqZ2xyp_i_U





### Get move by name
GET https://pokemonapi-mwwn.onrender.com/moves/transform
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzZjdjYWUyYjM3MGMwNjg0MDUwOGM2YyIsImdvb2dsZSI6eyJpZCI6IjEwNTA3ODIxODcwNjQ2Mjk3NDI5MSIsIm5hbWUiOiJEYW5pZWwgUmFzbXVzc2VuIiwiZW1haWwiOiJkYW5pZWxyYXNtdXNzZW40MkBnbWFpbC5jb20ifX0sImlhdCI6MTY3NzE4OTc3MSwiZXhwIjoxNjc3MTkzMzcxfQ.A-d724N195TYpNO3On6G8fcY3ZQzgjStMqZ2xyp_i_U

### Post a move
POST https://pokemonapi-mwwn.onrender.com/moves
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzZjdjYWUyYjM3MGMwNjg0MDUwOGM2YyIsImdvb2dsZSI6eyJpZCI6IjEwNTA3ODIxODcwNjQ2Mjk3NDI5MSIsIm5hbWUiOiJEYW5pZWwgUmFzbXVzc2VuIiwiZW1haWwiOiJkYW5pZWxyYXNtdXNzZW40MkBnbWFpbC5jb20ifX0sImlhdCI6MTY3NzE4OTc3MSwiZXhwIjoxNjc3MTkzMzcxfQ.A-d724N195TYpNO3On6G8fcY3ZQzgjStMqZ2xyp_i_U
content-type: application/json

{
	"name": "Charm",
	"type": "fairy",
	"power": "N/A",
	"accuracy": "100%"
}

### Put a move
PUT https://pokemonapi-mwwn.onrender.com/moves/63ded7c31e2a82519f4b07b1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzZjdjYWUyYjM3MGMwNjg0MDUwOGM2YyIsImdvb2dsZSI6eyJpZCI6IjEwNTA3ODIxODcwNjQ2Mjk3NDI5MSIsIm5hbWUiOiJEYW5pZWwgUmFzbXVzc2VuIiwiZW1haWwiOiJkYW5pZWxyYXNtdXNzZW40MkBnbWFpbC5jb20ifX0sImlhdCI6MTY3NzE4OTc3MSwiZXhwIjoxNjc3MTkzMzcxfQ.A-d724N195TYpNO3On6G8fcY3ZQzgjStMqZ2xyp_i_U
content-type: application/json

{
	"name": "charm",
	"type": "fairy",
	"power": "N/A",
	"accuracy": "100%"
}
### Delete a move
DELETE https://pokemonapi-mwwn.onrender.com/moves/63ded7c31e2a82519f4b07b1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7Il9pZCI6IjYzZjdjYWUyYjM3MGMwNjg0MDUwOGM2YyIsImdvb2dsZSI6eyJpZCI6IjEwNTA3ODIxODcwNjQ2Mjk3NDI5MSIsIm5hbWUiOiJEYW5pZWwgUmFzbXVzc2VuIiwiZW1haWwiOiJkYW5pZWxyYXNtdXNzZW40MkBnbWFpbC5jb20ifX0sImlhdCI6MTY3NzE4OTc3MSwiZXhwIjoxNjc3MTkzMzcxfQ.A-d724N195TYpNO3On6G8fcY3ZQzgjStMqZ2xyp_i_U
